### ISSUE TITLE
Critical CSS creates a new page entry for every query string

### ISSUE THREAD

**Issue by Schascha** [lenarother/django-critical-css#4]
Hi Magda, I hope you're doing well. Maybe there will be a possibility to reduce database entries. Critical CSS creates a new page entry for every query string:

![Bildschirmfoto 2020-08-25 um 11 16 40](https://user-images.githubusercontent.com/2518935/91157149-417edb80-e6c5-11ea-8f26-0e82ed956c4c.png)

In this above example it will produce nearly 1000 entries. Do you think it will be better to reduce the entries? 

Thanks, Sascha

**Comment by lenarother** [comment]
Hey @Schascha ,

I am very glad to hear from you, I hope you have a great start after your holiday. I assume that you've been greeted by a lot of critical objects. 

As to your request: I think there is a possibility that the query string is important for calculating the critical css - which is why I don't want to remove it completely. I've added a switch (setting) that allows you to ignore it. 

In order to benefit from the change you must:

- update the version to `dodjango-critical-css==0.0.3`. (https://pypi.org/project/django-critical-css/0.0.3/)
- add `CRITICAL_CSS_IGNORE_QUERY_STRING = True` in settings. (https://github.com/lenarother/django-critical-css/blob/master/docs/usage.rst#additional-settings)
- to clear the database from excessive number of objects you can use `python manage.py empty_critical_css`. (https://github.com/lenarother/django-critical-css/blob/master/docs/usage.rst#management-command-for-emptying-critical-css)

Cheers,
Magda
